# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-18 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('genre', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=50)),
                ('developer', models.CharField(max_length=50)),
                ('image', models.ImageField(default='media/None/no-img.jpg', upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('user_name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=2000)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Game')),
            ],
        ),
    ]
