# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-18 01:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='date released'),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 3, 18, 1, 8, 43, 833978, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(default='media/None/no-img.jpg', upload_to='media/'),
        ),
    ]
