# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-18 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20180318_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='release_date',
        ),
    ]
