# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(max_length=30),
        ),
    ]
