# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-23 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20180322_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='game',
            new_name='name',
        ),
    ]
