# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-23 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20180323_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='game',
        ),
    ]
