# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-23 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_game_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='slug',
        ),
    ]
