# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_remove_game_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='image',
            new_name='logo',
        ),
    ]
