# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20180323_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='UID',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
