# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-28 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_auto_20180328_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[(b'', b'Please Select'), (b'ACTION', b'Action'), (b'ACTIONADVENTURE', b'Action-Adventure'), (b'ADVENTURE', b'Adventure'), (b'MISC', b'Misc'), (b'RPG', b'Role-Playing Game'), (b'SIMULATION', b'Simulation'), (b'STRATEGY', b'Strategy'), (b'SPORTS', b'Sports'), (b'PUZZLE', b'Puzzle')], default=b'Please Select', max_length=17)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(default=b'None/no-img.jpg', upload_to=b'media/'),
        ),
    ]
